build:
  stage: build
  tags:
    - centos
  script:
    - module load gcc/6.2.0
    - module load boost/6.2.0-cmake
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j8
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build/

test:
  stage: test
  tags:
    - centos
  script:
    - cd build
    - make test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build/
