variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ssh_setup: &ssh_setup
- which ssh-agent || (which yum && yum install openssh-clients -y) || (which apt-get && apt-get install openssh-client -y)
- eval $(ssh-agent -s)
- echo $SCINE_DEPLOY_KEY | base64 -d | ssh-add -
- mkdir -p ~/.ssh
- chmod 700 ~/.ssh
- echo $SCINE_DEPLOY_HOSTS | base64 -d > ~/.ssh/known_hosts

.update_alternatives: &update_alternatives
- python --version
- update-alternatives --install /usr/bin/python python $(which python2) 1
- update-alternatives --install /usr/bin/python python $(which python3) 2
- python --version

.conan_setup: &conan_setup
- export CONAN_REVISIONS_ENABLED=1
- python --version
- python -m pip install --upgrade conan sphinx sphinx_rtd_theme pytest numpy
- conan remote add ci-internal $SCINE_DEPLOY_ARTIFACTORY_URL
- conan user -p $SCINE_DEPLOY_ARTIFACTORY_PASSWORD -r ci-internal $SCINE_DEPLOY_ARTIFACTORY_USERNAME

default:
  before_script:
    - *ssh_setup
    - *update_alternatives
    - *conan_setup

# Builds
coverage:
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  script:
    - python -m pip install --upgrade gcovr
    - mkdir -p build && cd build
    - conan install -o scine_molassembler:python=True -o scine_molassembler:tests=True -o scine_molassembler:docs=True -o scine_molassembler:coverage=True -s scine_molassembler:build_type=Debug ..
    - conan build ..
    - cd ..
    - python3 -m gcovr -r "$(pwd)/src/" -u --object-directory="$(pwd)/build/src/" --exclude-dir ".*test.*" --exclude-dir ".*extern.*" --exclude-dir ".*analysis.*" -e ".*extern.*" -e ".*test.*" --html --html-details -o coverage.html
    - python3 -m gcovr -r "$(pwd)/src/" -u --object-directory="$(pwd)/build/src/" --exclude-dir ".*test.*" --exclude-dir ".*extern.*" --exclude-dir ".*analysis.*" -e ".*extern.*" -e ".*test.*"
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    expire_in: 1 day
    paths:
    - coverage*.html

.conan_create: &conan_create
  tags:
    - default_docker
  script:
    - python --version
    - conan create -o scine_molassembler:python=True -o scine_molassembler:docs=True -o scine_molassembler:tests=True --build=missing --build=scine_molassembler . ci/$CI_COMMIT_REF_SLUG
    - if $CI_COMMIT_REF_PROTECTED; then conan upload `conan search scine_molassembler | tail -n1` --all -r ci-internal -c; fi

gcc-release:
  <<: *conan_create
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest


clang-release:
  <<: *conan_create
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-clang:latest


pypi:
  tags:
    - default_docker
  image: quay.io/pypa/manylinux2014_x86_64
  before_script:
    - *ssh_setup
    - /opt/python/cp36-cp36m/bin/python -m venv cp36-cp36m
    - source cp36-cp36m/bin/activate
    - *conan_setup
  script:
    - python -m pip install wheel
    - mkdir -p build && cd build
    - conan install -o scine_molassembler:python=True -o scine_utilities:shared=False -o scine_molassembler:shared=False -o scine_molassembler:microarch=none --build=missing ..
    - conan build ..
    - cd src/molassembler/python
    - python setup.py bdist_wheel
    - auditwheel show dist/*.whl
    - auditwheel repair dist/*.whl
    - cd wheelhouse && python -c 'import os; n=os.listdir()[0]; os.rename(n, n.replace("py3-none", "cp36-cp36m"))'
  artifacts:
    expire_in: 1 day
    paths:
    - build/src/molassembler/python/wheelhouse

# Quality
license:
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  before_script:
    - echo "Skip before_script"
  script:
    - bash scripts/license_validity_check.sh

complexity:
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  before_script:
    - echo "Skip before_script"
  script:
    - python3 -m pip install lizard jinja2
    - cd src
    - lizard -l cpp -m -T nloc=100 -T cyclomatic_complexity=15 -T parameter_count=5 -x "./extern/*" -o lizard.html
    - lizard -l cpp -m -w -s cyclomatic_complexity -T cyclomatic_complexity=20 -x "./extern/*" -x "*/analysis/*" -W ../.whitelizard.txt
  artifacts:
    expire_in: 1 day
    paths:
      - src/lizard.html
