#
# Define the CI stages
#
stages:
  - build
  - test
  - quality_checks

#
# GCC Debug test and coverage
#
build:gcc_debug:
  stage: build
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  script:
    - mkdir -p build_gcc_debug
    - cd build_gcc_debug
    - pwd
    - cmake -DMOLASSEMBLER_DOWNLOAD_DEPENDENCIES=ON -DCMAKE_CXX_FLAGS="-g -O0 -coverage" -DCMAKE_EXE_LINKER_FLAGS="-coverage" ..
    - make -j8
  artifacts:
    expire_in: 1 day
    paths:
      - build_gcc_debug

test:gcc_debug:
  stage: test
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  script:
    - (cd build_gcc_debug && make check)
    - python $(which gcovr) -r "$(pwd)/src/" -u --object-directory="$(pwd)/build_gcc_debug/src/" --exclude-dir ".*test.*" --exclude-dir ".*extern.*" --exclude-dir ".*analysis.*" -e ".*extern.*" -e ".*test.*"
  dependencies:
    - build:gcc_debug
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    expire_in: 1 day

#
# GCC Release test
#
build:gcc_release:
  stage: build
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  script:
    - mkdir -p build_gcc_release
    - cd build_gcc_release
    - pwd
    - cmake -DCMAKE_BUILD_TYPE=Release -DMOLASSEMBLER_DOWNLOAD_DEPENDENCIES=ON ..
    - make -j8
  artifacts:
    expire_in: 1 day
    paths:
      - build_gcc_release

test:gcc_release:
  stage: test
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  script:
    - (cd build_gcc_release && make check)
  dependencies:
    - build:gcc_release
  artifacts:
    expire_in: 1 day


#
# Clang Release test
#
build:clang_release:
  stage: build
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-clang:latest
  only:
    - master
  script:
    - mkdir -p build_clang
    - cd build_clang
    - pwd
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DMOLASSEMBLER_DOWNLOAD_DEPENDENCIES=ON ..
    - make -j8
  artifacts:
    expire_in: 1 day
    paths:
      - build_clang

test:clang_release:
  stage: test
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-clang:latest
  only:
    - master
  script:
    - (cd build_clang && make check)
  dependencies:
    - build:clang_release
  artifacts:
    expire_in: 1 day

#
# Verify that the ETH license is present in all source files
#
eth_license:
  stage: quality_checks
  tags:
    - default_docker
  image: gitlab.chab.ethz.ch:4567/reiher/docker/scine-gcc:latest
  script:
    - bash scripts/license_validity_check.sh
