stages:
  - build
  - test

gcc-build:
  stage: build
  tags:
    - centos
  script:
    - ls
    - module purge
    - module load module_include_dir gcc/7.3.0 boost/gcc-7.3.0/1.64.0-cmake Eigen/3.3.2-cmake dlib/gcc-7.3.0/19.10-cmake
    - mkdir -p build-gcc
    - cd build-gcc
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/scratch/sobezj/installs/scine/gcc-7.3.0/0.2.0/ ..
    - make
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-gcc/

gcc-test:
  stage: test
  tags:
    - centos
  script:
    - module purge
    - module load module_include_dir gcc/7.3.0 boost/gcc-7.3.0/1.64.0-cmake
    - cd build-gcc
    - make test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-gcc/
    policy: pull

clang-build:
  stage: build
  tags:
    - centos
  script:
    - ls
    - module purge
    - module load module_include_dir gcc/7.3.0 clang/6.0.0 boost/clang-6.0.0/1.64.0-cmake Eigen/3.3.2-cmake dlib/gcc-7.3.0/19.10-cmake
    - mkdir -p build-clang
    - cd build-clang
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/scratch/sobezj/installs/scine/clang-6.0.0/0.2.0/ ..
    - make
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-clang/

clang-test:
  stage: test
  tags:
    - centos
  script:
    - module purge
    - module load module_include_dir gcc/7.3.0 clang/6.0.0 boost/clang-6.0.0/1.64.0-cmake
    - cd build-clang
    - make test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-clang/
    policy: pull
