stages:
  - build-dependencies
  - build
  - test

scine-build:
  stage: build-dependencies
  tags:
    - centos
  script:
    - git clone --depth 1 git@gitlab.chab.ethz.ch:scine/scine.git -b develop
    - module purge
    - module load module_include_dir gcc/7.3.0 boost/gcc-7.3.0/1.64.0-cmake Eigen/3.3.2-cmake
    - mkdir scine-build
    - cd scine-build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../scine-install -DSCINE_INSTALL_DEV_FILES=ON -DSCINE_INCLUDE_PROJECT_DIRS=Utilities/CppUtil\;Utilities/Delib/lib ../scine
    - make
    - make install
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - scine-install/

gcc-build:
  stage: build
  tags:
    - centos
  script:
    - module purge
    - module load module_include_dir gcc/7.3.0 boost/gcc-7.3.0/1.64.0-cmake Eigen/3.3.2-cmake dlib/gcc-7.3.0/19.10-cmake
    - mkdir -p build-gcc
    - cd build-gcc
    - cmake -DCMAKE_BUILD_TYPE=Release -Dscine_DIR=../scine-install/lib/cmake/scine ..
    - make
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-gcc/

gcc-test:
  stage: test
  tags:
    - centos
  script:
    - module purge
    - module load module_include_dir gcc/7.3.0 boost/gcc-7.3.0/1.64.0-cmake
    - cd build-gcc
    - make test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-gcc/

clang-build:
  stage: build
  tags:
    - centos
  script:
    - module purge
    - module load module_include_dir gcc/7.3.0 clang/6.0 boost/clang-6.0.0/1.64.0-cmake Eigen/3.3.2-cmake dlib/gcc-7.3.0/19.10-cmake
    - mkdir -p build-clang
    - cd build-clang
    - cmake -DCMAKE_BUILD_TYPE=Release -Dscine_DIR=../scine-install/lib/cmake/scine ..
    - make
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-clang/

clang-test:
  stage: test
  tags:
    - centos
  script:
    - module purge
    - module load module_include_dir gcc/7.3.0 clang/6.0 boost/clang-6.0.0/1.64.0-cmake
    - cd build-clang
    - make test
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
    - build-clang/
